export const palette = {
  background: '#F9FAFB',
  textPrimary: '#1F2937',
  textSecondary: '#6B7280',
  textPlaceholder: '#9CA3AF',
  textInverse: '#FFFFFF',
  brandBlue: '#0066CC',
  brandBlueAndroid: '#0066CC',
  disabledBgIOS: '#E5E7EB',
  disabledBgAndroid: '#E5E7EB',
  disabledTextIOS: '#D1D5DB',
  disabledTextAndroid: '#D1D5DB',
  white: '#FFFFFF',
  transparent: 'transparent',
  surface: '#FFFFFF',
  border: '#E5E7EB',
  stateError: '#DC2626',
  stateErrorText: '#991B1B',
};
