#!/usr/bin/env node
/* eslint-disable @typescript-eslint/no-require-imports */

/**
 * Mobile design token build script using Style Dictionary.
 * Reads the design tokens from the shared design-documentation package and emits
 * value-only outputs into src/theme/generated for React Native consumption.
 */

const fs = require('node:fs');
const path = require('node:path');
const StyleDictionary = require('style-dictionary');

const { formatHelpers } = StyleDictionary;

const projectRoot = path.resolve(__dirname, '..', '..');
const designTokensPath = path.resolve(
  projectRoot,
  '..',
  'design-documentation',
  'assets',
  'design-tokens.json'
);
const buildPath = 'src/theme/generated/';

if (!fs.existsSync(designTokensPath)) {
  throw new Error(`Design tokens not found at ${designTokensPath}`);
}

StyleDictionary.registerTransformGroup({
  name: 'mobile/identity',
  transforms: ['name/cti/camel'],
});

StyleDictionary.registerFormat({
  name: 'typescript/es6-const',
  formatter: ({ dictionary }) => {
    const tokens = formatHelpers.minifyDictionary(dictionary.tokens);
    return [
      '// Auto-generated by tokens:build:mobile. Do not edit manually.',
      `const tokens = ${JSON.stringify(tokens, null, 2)} as const;`,
      '',
      'export default tokens;',
      '',
    ].join('\n');
  },
});

StyleDictionary.registerFormat({
  name: 'typescript/tokens-declaration',
  formatter: () =>
    [
      '// Auto-generated by tokens:build:mobile. Do not edit manually.',
      "import tokens from './tokens';",
      '',
      'export type Tokens = typeof tokens;',
      '',
      'export default tokens;',
      '',
    ].join('\n'),
});

const sd = StyleDictionary.extend({
  source: [designTokensPath],
  platforms: {
    mobile: {
      transformGroup: 'mobile/identity',
      buildPath,
      files: [
        { destination: 'tokens.raw.json', format: 'json/nested' },
        { destination: 'tokens.ts', format: 'typescript/es6-const' },
        { destination: 'tokens.d.ts', format: 'typescript/tokens-declaration' },
      ],
    },
  },
});

sd.buildPlatform('mobile');

console.log(
  'Mobile tokens built at',
  path.join(buildPath, 'tokens.raw.json'),
  'and',
  path.join(buildPath, 'tokens.ts')
);
