#!/usr/bin/env node

/**
 * Mobile design token build script.
 * Reads the design tokens from the shared design-documentation package and emits
 * value-only outputs into src/theme/generated for React Native consumption.
 */

const fs = require('node:fs');
const path = require('node:path');

const projectRoot = path.resolve(__dirname, '..', '..');
const designTokensPath = path.resolve(projectRoot, '..', 'design-documentation', 'assets', 'design-tokens.json');
const outputDir = path.resolve(projectRoot, 'src', 'theme', 'generated');
const rawOutputPath = path.join(outputDir, 'tokens.raw.json');
const tsOutputPath = path.join(outputDir, 'tokens.ts');

function readDesignTokens() {
  if (!fs.existsSync(designTokensPath)) {
    throw new Error(`Design tokens not found at ${designTokensPath}`);
  }

  const contents = fs.readFileSync(designTokensPath, 'utf8');
  return JSON.parse(contents);
}

function toValueTree(node) {
  if (Array.isArray(node)) {
    return node.map(toValueTree);
  }

  if (node && typeof node === 'object') {
    if (Object.prototype.hasOwnProperty.call(node, 'value')) {
      return node.value;
    }

    return Object.entries(node).reduce((acc, [key, value]) => {
      acc[key] = toValueTree(value);
      return acc;
    }, {});
  }

  return node;
}

function writeFile(filePath, contents) {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, contents);
}

function build() {
  const designTokens = readDesignTokens();
  const valueTree = toValueTree(designTokens);

  writeFile(rawOutputPath, `${JSON.stringify(valueTree, null, 2)}\n`);

  const tsBody = `// Auto-generated by tokens:build:mobile. Do not edit manually.\nconst tokens = ${JSON.stringify(
    valueTree,
    null,
    2
  )} as const;\n\nexport default tokens;\n`;

  writeFile(tsOutputPath, tsBody);

  // eslint-disable-next-line no-console
  console.log('Generated mobile tokens:', path.relative(projectRoot, rawOutputPath), path.relative(projectRoot, tsOutputPath));
}

build();
